[Service]
User=postgres
NoNewPrivileges=yes
RestrictNamespaces=yes
RestrictSUIDSGID=yes
RestrictRealtime=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectHome=no
ProtectClock=yes
ProtectProc=invisible
ProcSubset=pid
LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
RemoveIPC=no